# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1409ac1880f4e5548ba4b625de075540eb81789d1f4c39e468c3f002e59a15d598ab244ad712489617f7c2b77b9173d13855cc832544bb17fe1fec6f9452492

test:
  secret_key_base: 5ac3b3fff41340cbdf5056f5230cee1b5cb56810b6f9062ac1c9fd05c8e73c625083d82acbfe0a01716ea24ec2ffa483f1797182c64c5fa8c9901413cecee6c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
